### ISSUE TITLE
unoconvert no longer works

### ISSUE THREAD

**Issue by jimisola** [unoconv/unoserver-docker#11]
I don't use this container image myself any longer and just noticed that it does not seem to work.
Currently, no idea of what is causing it.

3 options for now:

1. My changes have caused it: does not with the previously released image, so probably not it.
2. Changes to alpine
3. Changes to libreoffice including libreoffice in alpine
4. Changes to unoserver pypi package:

```
worker@79b332138931:/data$ unoconvert test.docx test.pdf
INFO:unoserver:Starting unoconverter.
INFO:unoserver:Opening test.docx
INFO:unoserver:Exporting to test.pdf
INFO:unoserver:Using writer_pdf_Export export filter
Traceback (most recent call last):
  File "/usr/bin/unoconvert", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/unoserver/converter.py", line 307, in main
    result = converter.convert(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/unoserver/converter.py", line 241, in convert
    document.storeToURL(export_path, output_props)
unoserver.converter.com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///data/test.pdf> failed: 0x507(Error Area:Io Class:Access Code:7) at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.5.3.2/sfx2/source/doc/sfxbasemodel.cxx:3213 at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.5.3.2/sfx2/source/doc/sfxbasemodel.cxx:1789
```

```
worker@79b332138931:/data$ python find_uno.py 
Trying python found at /usr/bin/python3... Success!
Trying python found at /usr/bin/python... Success!
Found 2 Pythons with Libreoffice libraries:
/usr/bin/python3
/usr/bin/python
worker@79b332138931:/data$ 
```

**Comment by jimisola** [comment]
@regebro Are you aware of any relevant changes or do you  even recognize the error message?

**Comment by jimisola** [comment]
@regebro I would like to delete this issue and also this https://github.com/unoconv/unoserver-docker/issues/8 

Can you do it or do it for me?

**Comment by regebro** [comment]
Yup.
