### ISSUE TITLE
unoconvert outfile can't set to /data folder

### ISSUE THREAD

**Issue by Kain-90** [unoconv/unoserver-docker#69]
docker-compose start command:
```
unoserver:
    image: ghcr.io/unoconv/unoserver-docker:0.3.21
    restart: always
    volumes:
      - ./volumes/unoserver:/data
```

After container is started, i paste a doc file to `./volumes/unoserver`, and use below commands try to convert doc file to docx file.

```
docker exec -it --user root unoserver bash

d38b2bf7077b:/data# ls -alh /
total 80K    
drwxr-xr-x    1 root     root        4.0K Oct 24 09:22 .
drwxr-xr-x    1 root     root        4.0K Oct 24 09:22 ..
-rwxr-xr-x    1 root     root           0 Oct 24 09:22 .dockerenv
-rwxrwxr-x    1 root     root        1.1K Jan 27  2024 __cacert_entrypoint.sh
drwxr-xr-x    1 root     root        4.0K Mar  1  2024 bin
drwxr-xr-x    2 root     root          79 Oct 24 12:04 data
drwxr-xr-x    5 root     root         340 Oct 24 12:01 dev
-rwxr-xr-x    1 worker   worker      1.4K Mar  1  2024 entrypoint.sh
drwxr-xr-x    1 root     root        4.0K Oct 24 09:22 etc
drwxr-xr-x    1 root     root        4.0K Mar  1  2024 home

d38b2bf7077b:/data# ls -alh /data
total 620K   
drwxr-xr-x    2 root     root          79 Oct 24 12:04 .
drwxr-xr-x    1 root     root        4.0K Oct 24 09:22 ..
-rw-r--r--    1 root     root      613.5K Oct 24 12:02 92ccaa67-a033-42eb-9301-ebf8017b1fd3.doc
-rw-r--r--    1 root     root           0 Oct 24 12:04 a.txt
-rw-r--r--    1 root     root           0 Oct 24 12:04 atou

# adding any file by touch command in /data directory is ok

# error
d38b2bf7077b:/data# unoconvert /data/92ccaa67-a033-42eb-9301-ebf8017b1fd3.doc /data/92ccaa67-a033-42eb-9301-ebf8017b1fd3.docx
Traceback (most recent call last):
  File "/usr/bin/unoconvert", line 8, in <module>
    sys.exit(converter_main())
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/unoserver/client.py", line 248, in converter_main
    result = client.convert(
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/unoserver/client.py", line 87, in convert
    result = proxy.convert(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
           ^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'unoserver.converter.com.sun.star.io.IOException'>:SfxBaseModel::impl_store <file:///data/92ccaa67-a033-42eb-9301-ebf8017b1fd3.docx> failed: 0x507(Error Area:Io Class:Access Code:7) at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.6.3.1/sfx2/source/doc/sfxbasemodel.cxx:3221 at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.6.3.1/sfx2/source/doc/sfxbasemodel.cxx:1792">


# but below command is OK
unoconvert /data/92ccaa67-a033-42eb-9301-ebf8017b1fd3.doc /tmp/92ccaa67-a033-42eb-9301-ebf8017b1fd3.docx
```

**Comment by Kain-90** [comment]
Alright, i fixed this issue by myself.

Before i execute unoconvert, i have to do this first. `chmod 777 /data`.
