### ISSUE TITLE
Crash at startup due to connexion error

### ISSUE THREAD

**Issue by Aegdesil** [unoconv/unoserver-docker#75]
When starting the container, I sometimes have this log:

```
2024-12-06T11:51:53.206046650Z using: LibreOffice 7.6.7.2 60(Build:2)
2024-12-06T11:51:53.206302472Z Running unoserver-docker in non-interactive.
2024-12-06T11:51:53.206362697Z For interactive mode use '-it', e.g. 'docker run -v /tmp:/data -it unoserver/unoserver-docker'.
2024-12-06T11:51:54.967482521Z INFO:unoserver:Starting unoserver 3.0.1.
2024-12-06T11:51:54.967893786Z INFO:unoserver:Command: /usr/bin/soffice --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmpudpx_gho --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
2024-12-06T11:52:05.040349865Z INFO:unoserver:Starting UnoConverter.
2024-12-06T11:52:05.060533225Z Exception in thread Thread-1 (serve):
2024-12-06T11:52:05.060587570Z Traceback (most recent call last):
2024-12-06T11:52:05.060596136Z   File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
2024-12-06T11:52:05.061627199Z     self.run()
2024-12-06T11:52:05.061786897Z   File "/usr/lib/python3.12/threading.py", line 1012, in run
2024-12-06T11:52:05.062492710Z     self._target(*self._args, **self._kwargs)
2024-12-06T11:52:05.062716960Z   File "/usr/lib/python3.12/site-packages/unoserver/server.py", line 131, in serve
2024-12-06T11:52:05.064504401Z     self.conv = converter.UnoConverter(
2024-12-06T11:52:05.064532172Z                 ^^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T11:52:05.064539967Z   File "/usr/lib/python3.12/site-packages/unoserver/converter.py", line 77, in __init__
2024-12-06T11:52:05.066046191Z     self.context = self.resolver.resolve(
2024-12-06T11:52:05.066073684Z                    ^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T11:52:05.066168577Z unoserver.converter.com.sun.star.connection.NoConnectException: Connector : couldn't connect to socket (Connection refused) at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.6.7.2/io/source/connector/connector.cxx:118
2024-12-06T11:52:06.974740268Z INFO:unoserver:Failed to start servers
```

This does not happen systematically, I suspect some race condition, maybe when the host is too slow to start the server ?
Restarting the container fixes the problem, but it is annoying to do regularly.

Is there a way to add a retry / longer timeout ?

**Comment by Aegdesil** [comment]
Here is another similar log 
```
using: LibreOffice 7.6.7.2 60(Build:2)
Running unoserver-docker in non-interactive.
For interactive mode use '-it', e.g. 'docker run -v /tmp:/data -it unoserver/unoserver-docker'.
INFO:unoserver:Starting unoserver 3.0.1.
INFO:unoserver:Command: /usr/bin/soffice --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmpxnz56_15 --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
INFO:unoserver:Starting UnoConverter.
INFO:unoserver:Starting UnoComparer.
Exception in thread Thread-1 (serve):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/unoserver/server.py", line 134, in serve
    self.comp = comparer.UnoComparer(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/unoserver/comparer.py", line 69, in __init__
    self.context = self.resolver.resolve(
                   ^^^^^^^^^^^^^^^^^^^^^^
unoserver.comparer.com.sun.star.lang.DisposedException: Binary URP bridge disposed during call at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.6.7.2/binaryurp/source/bridge.cxx:615
INFO:unoserver:Failed to start servers
```

**Comment by jimisola** [comment]
@regebro Do you have any input here? The main change in the docker is an upgrade of unoserver.

**Comment by regebro** [comment]
It could be that it's slow to start, and that the code that improves the handling of what happens when LibreOffice isn't started then errors out. 

"Binary URP bridge disposed" is strange, that sounds like Libreoffice crashed during the call. But the first error could be a timeout. 

I'll look into if I can handle that better.

**Comment by jimisola** [comment]
@regebro Thanks. Any updates?

**Comment by jimisola** [comment]
@regebro Any updates? Not sure if there is anything that I can change in the container image.

**Comment by regebro** [comment]
Merry Christmas!

**Comment by Aegdesil** [comment]
Hello @regebro, do you have any updates regarding this issue ?

**Comment by jon-hedgerows** [comment]
I've been seeing this as well, same error as above.

I suspect what's happening is that the multithreading in unoserver naively assumes that the server starts within 2 seconds.  if it doesn't it simply fails. On one of my servers (an old i5 something or other) it takes ~1.9s to start up; on my raspberry pi it reliably takes more than 2s, so never starts.

a naive fix would be to extend the timeout here:
https://github.com/unoconv/unoserver/blob/a53ae677220e9ee00f505a0580d99436bec990eb/src/unoserver/server.py#L119

but a better fix would be to add a much longer back-off loop, dropping out as soon as the connection is possible.

**Comment by elshev** [comment]
I reproduced it on Windows WSL on the latest version by limiting the resources for the container:
`docker run -d --name unoserver-docker --cpus=0.1 -m 64m --memory-swap=128m unoserver-docker`.

Logs are:
```
using: LibreOffice 7.6.7.2 60(Build:2)
Running unoserver-docker in non-interactive.
For interactive mode use '-it', e.g. 'docker run -v /tmp:/data -it unoserver/unoserver-docker'.
INFO:unoserver:Starting unoserver 3.1.
INFO:unoserver:Command: /usr/bin/soffice --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmp74g34uq8 --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
INFO:unoserver:Starting UnoConverter.
Exception in thread Thread-1 (serve):
Traceback (most recent call last):
File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
File "/usr/lib/python3.12/threading.py", line 1012, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.12/site-packages/unoserver/server.py", line 131, in serve
self.conv = converter.UnoConverter(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/unoserver/converter.py", line 77, in __init__
self.context = self.resolver.resolve(
^^^^^^^^^^^^^^^^^^^^^^
unoserver.converter.com.sun.star.connection.NoConnectException: Connector : couldn't connect to socket (Connection refused) at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.6.7.2/io/source/connector/connector.cxx:118
INFO:unoserver:Failed to start servers
```

**Comment by jimisola** [comment]
@regebro Was this something that you were going to luck at in unoserver?

**Comment by regebro** [comment]
The startup is more resilient now, and that should help.

**Comment by jimisola** [comment]
Ok. I'll make a new release with the latest version of unoserver when I have the time.

**Comment by jimisola** [comment]
I'll close this as I believe that it has been fixed by @regebro and there has been no activity here for some time.
